### PR TITLE
Added favicon.ico

### PR DESCRIPTION
**Pull request by jojo935**
Thought I'd add the favicon.ico that admin liked. Would look better than having no favicon at all

### CODE REVIEW

**Comment by kemono-bugs** [comment]
Sorry I forgot about this, intended to add it at some point but got sidetracked. Thanks for the contribution!

**Comment by BassOfBass** [comment]
@jojo935 do you have an `.svg` version of this icon? It will become handy in the future.

**Comment by jojo935** [comment]
I do indeed. Here it is.
________________________________

**Comment by BassOfBass** [comment]
@jojo935 I don't see anything in your post. If you've gotten it somewhere else, post the link to its page instead. If you've made it yourself, submit with another PR. Don't forget to add loicense in that case.

**Comment by jojo935** [comment]
I May as well upload it to my secondary acc's drive and do it that way since all my kemono related stuff is on there. I'll reply with a link when I add everything there.

**Comment by jojo935** [comment]
Here's a link to the drive file. Has a .svg and .png of the image, alongside an alternative one that admin didn't really like.

**Pull request merged**
